### ISSUE TITLE
Chart not display no error in debug

### ISSUE THREAD

**Issue by AmauryBJ** [mr-azazael/LightweightCharts.Blazor#4]
i Created a simple blazor project and try to integrate the chart without any success. 
Your example is working but cannot succeed with mine, i tried :

- Putting the project in .net 6 (Your example projet are not working in .net 7)
- Importing your data source to be sur it's not the problem
- cloning the complete project and referencing it to be ale to debug (No error in VS or in JS)

You can find my test project here : [BlazorApp1.zip](https://github.com/mr-azazael/LightweightCharts.Blazor/files/13702797/BlazorApp1.zip)
I integrate TW Chart under the Counter Page

Thanks a lot 
Amaury

**Comment by kiranmaya** [comment]
i have the same issue, able to run sample project samples, but not into the main project, have you solved it?
nuget version not working , works fine with GitHub  project reference

**Comment by mr-azazael** [comment]
@AmauryBJ The (first) issue is that in the default project template, some elements aren't configured to stretch to 100% height. The element in cause is in MainLayout.razor, <article class="content px-4>.
Just add a h-100 to its class, if you're using bootstrap.

Another issue is with the AutoResize flag (set to true by default) in the 3.8.0 package, it's causing either an exception, which is fixed in the main branch already or the chart keeps stretching vertically forever (still looking for a way to handle the resize gracefully).
A simple (temporary) fix is to set AutoResize=false and use chart.ApplyOptions to set a predefined width/height.
Keep an eye for a commit in the coming days.

@kiranmaya I think you might have the same issue.

**Comment by kiranmaya** [comment]
@mr-azazael okay, waiting for your update, Great work man.

**Comment by mr-azazael** [comment]
I'm closing this as the issue was from the page layout, not an issue with the wrapper.

**Comment by mr-azazael** [comment]
I'm closing this as the issue was from the page layout, not an issue with the wrapper.
